/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:921b8570-80d7-48e2-8a15-735fd4403a10",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Edax2VgiJ",
    "aws_user_pools_web_client_id": "67kvtju6ok0cmr8lpg4m0srnb9",
    "oauth": {},
    "aws_user_files_s3_bucket": "userdata43220-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://hv5ozgy5bvdmxhoovdtsmycc6u.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
